version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DB_NAME=internmatch
      - PORT=8000
    ports:
      - "8000:8000"

volumes:
  mongo_data:
